# Assignment 1 by Geeta Singh

### Question 1

1. Find out the mean and standard deviation of the heights across all the baseball players. The
mean and standard deviaion of a numpy array can be computed by np.mean() and np.std(),
respectively.
1
2. Subtract the mean from each height.
3. Divide the values in the second step (mean is already subtracted) by its standard deviation.

In [16]:
# Answer 1
import numpy as np
height = [72,78, 69,71,76, 79]
np_height = np.array(height)
np_mean = np.mean(height)
np_standard_deviation = np.std(height)
height_s = (np_height - np_mean)/np_standard_deviation
print(height_s)

[-0.5831297   1.031691   -1.39054004 -0.85226648  0.49341743  1.30082778]


### Question 2
Beginning of second question.

In [83]:
#2
from sklearn.datasets import load_boston
boston = load_boston()
attr = boston.data # attributes that may affact median values
medV = boston.target # median value
print(boston.feature_names)
print( boston.DESCR )

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial hig

#### Question 2.1
Print out the 10th row of attr.

In [84]:
# Answer 2.1
print(attr[9,])


[1.7004e-01 1.2500e+01 7.8700e+00 0.0000e+00 5.2400e-01 6.0040e+00
 8.5900e+01 6.5921e+00 5.0000e+00 3.1100e+02 1.5200e+01 3.8671e+02
 1.7100e+01]


#### Question 2.2
Print out the average number of rooms per dwelling (RM) of the 20th tract.

In [40]:
# Answer 2.2 
print(attr[19, 5])

5.727


#### Question 2.3 
Print out all observations whose median values are small than 6. You do not need to include
the median value column in your output.

In [67]:
#Answer 2.3 
medV_lessthan_six = medV < 6
filtered_attr_lessthan_six = attr[medV_lessthan_six]
print(filtered_attr_lessthan_six)



[[ 38.3518   0.      18.1      0.       0.693    5.453  100.       1.4896
   24.     666.      20.2    396.9     30.59  ]
 [ 25.0461   0.      18.1      0.       0.693    5.987  100.       1.5888
   24.     666.      20.2    396.9     26.77  ]
 [ 67.9208   0.      18.1      0.       0.693    5.683  100.       1.4254
   24.     666.      20.2    384.97    22.98  ]]


#### Question 2.4
Print out the average pupil-teacher ratio (PTRATIO) of all the towns whose median values are
small than 20.

In [68]:
#Answer 2.4
medV_lessthan_20 = medV < 20
filtered_20_attr = attr[medV_lessthan_20]
filtered_by_pupil = filtered_20_attr[0:, 10:11]
np.average(filtered_by_pupil)

19.485238095238092

#### Question 2.5
Use numpy array indexing to select and print out INDUS, TAX and LSTAT of the first 5 towns.

In [74]:
print(attr[0:5,[2,9,12]])

[[  2.31 296.     4.98]
 [  7.07 242.     9.14]
 [  7.07 242.     4.03]
 [  2.18 222.     2.94]
 [  2.18 222.     5.33]]


### Question 3

Write a function my_f(a) that takes a list a as input and computes 6x2 + 2 for every element x
in the list a, so that if we execute the following codes, the printed output will be [ 8 56 152].
Complete the definition of my_f function.

In [76]:
def my_f(a):
    final_list = []
    for x in a:
        result = 6*(x)**2 + 2
        final_list.append(result) 
    return final_list

my_f( [1,3,5] )

[8, 56, 152]

In [78]:
def my_f(a):
    return [6*x**2 + 2 for x in a]

my_f([1,3,5])

[8, 56, 152]